
production:
  adapter: postgresql
  database: <%= ENV['PG_DB_NAME'] %>
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: <%= ENV['PG_DB'] %>
  port: 5432

development:
  adapter: postgresql
  database: buckets
  username: buckets
  password: 
  host: localhost
  port: 5432
